# Generated by Django 4.1.5 on 2023-01-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("static_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="pics")),
                ("name", models.CharField(max_length=250)),
                ("desc", models.TextField()),
            ],
        ),
    ]
