# Generated by Django 4.1.5 on 2023-01-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("static_app", "0002_people"),
    ]

    operations = [
        migrations.RenameField(
            model_name="people",
            old_name="desc",
            new_name="desc1",
        ),
        migrations.RenameField(
            model_name="people",
            old_name="img",
            new_name="img1",
        ),
        migrations.RenameField(
            model_name="people",
            old_name="name",
            new_name="name1",
        ),
    ]
