# Generated by Django 4.1.5 on 2023-01-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("static_app", "0003_rename_desc_people_desc1_rename_img_people_img1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="people",
            old_name="desc1",
            new_name="desc",
        ),
        migrations.RenameField(
            model_name="people",
            old_name="img1",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="people",
            old_name="name1",
            new_name="name",
        ),
    ]
